//Apache NetBeans IDE 22
//Nome: Abhimael Sidney Setni Rogatti RA: 2618001

import javax.swing.JOptionPane;

public class Principal extends javax.swing.JFrame {
    private static Principal mainUnic;
    
    private FormEquipe formEquipe;
    private FormAgenda formAgenda;
    private FormFuncionario formFuncionario;
    private FormJog formJog;
    private FormPres formPres;
    private FormTec formTec;
    
    private Principal() {
        initComponents();
    }
    
    //Singleton
    public static Principal getInstancia(){
        if(mainUnic == null){
            mainUnic = new Principal();
            return mainUnic;
        }
        return mainUnic;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbPrincipal = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuMenu = new javax.swing.JMenu();
        itMenuFormEquipe = new javax.swing.JMenuItem();
        itMenuFormFuncionario = new javax.swing.JMenuItem();
        itMenuFormPresidente = new javax.swing.JMenuItem();
        itMenuFormJogador = new javax.swing.JMenuItem();
        itMenuFormTecnico = new javax.swing.JMenuItem();
        itMenuFormAgenda = new javax.swing.JMenuItem();
        itMenuSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        itMenuSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestor de Equipe");

        lbPrincipal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbPrincipal.setText("SISTEMA DE GERENCIAMENTO DE EQUIPE");

        menuMenu.setText("Menu");

        itMenuFormEquipe.setMnemonic('E');
        itMenuFormEquipe.setText("Equipe...");
        itMenuFormEquipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMenuFormEquipeActionPerformed(evt);
            }
        });
        menuMenu.add(itMenuFormEquipe);

        itMenuFormFuncionario.setMnemonic('F');
        itMenuFormFuncionario.setText("Funcionário...");
        itMenuFormFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMenuFormFuncionarioActionPerformed(evt);
            }
        });
        menuMenu.add(itMenuFormFuncionario);

        itMenuFormPresidente.setMnemonic('P');
        itMenuFormPresidente.setText("Presidente...");
        itMenuFormPresidente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMenuFormPresidenteActionPerformed(evt);
            }
        });
        menuMenu.add(itMenuFormPresidente);

        itMenuFormJogador.setMnemonic('J');
        itMenuFormJogador.setText("Jogador...");
        itMenuFormJogador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMenuFormJogadorActionPerformed(evt);
            }
        });
        menuMenu.add(itMenuFormJogador);

        itMenuFormTecnico.setMnemonic('T');
        itMenuFormTecnico.setText("Técnico...");
        itMenuFormTecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMenuFormTecnicoActionPerformed(evt);
            }
        });
        menuMenu.add(itMenuFormTecnico);

        itMenuFormAgenda.setMnemonic('A');
        itMenuFormAgenda.setText("Agenda...");
        itMenuFormAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMenuFormAgendaActionPerformed(evt);
            }
        });
        menuMenu.add(itMenuFormAgenda);

        itMenuSair.setMnemonic('S');
        itMenuSair.setText("Sair");
        itMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMenuSairActionPerformed(evt);
            }
        });
        menuMenu.add(itMenuSair);

        jMenuBar1.add(menuMenu);

        jMenu2.setText("Ajuda");

        itMenuSobre.setMnemonic('S');
        itMenuSobre.setText("Sobre...");
        itMenuSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMenuSobreActionPerformed(evt);
            }
        });
        jMenu2.add(itMenuSobre);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(lbPrincipal)
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(lbPrincipal)
                .addContainerGap(182, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itMenuFormFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMenuFormFuncionarioActionPerformed
        abrirFormFunc();
    }//GEN-LAST:event_itMenuFormFuncionarioActionPerformed

    private void itMenuFormJogadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMenuFormJogadorActionPerformed
        abrirFormJog();
    }//GEN-LAST:event_itMenuFormJogadorActionPerformed

    private void itMenuFormAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMenuFormAgendaActionPerformed
        abrirFormAgenda();
    }//GEN-LAST:event_itMenuFormAgendaActionPerformed

    private void itMenuFormTecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMenuFormTecnicoActionPerformed
        abrirFormTec();
    }//GEN-LAST:event_itMenuFormTecnicoActionPerformed

    private void itMenuFormPresidenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMenuFormPresidenteActionPerformed
        abrirFormPres();
    }//GEN-LAST:event_itMenuFormPresidenteActionPerformed

    private void itMenuFormEquipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMenuFormEquipeActionPerformed
        abrirFormEquipe();
    }//GEN-LAST:event_itMenuFormEquipeActionPerformed

    private void itMenuSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMenuSobreActionPerformed
        JOptionPane.showMessageDialog(null, "Este Sistema foi feito para gerenciar uma equipe tradicional de esportes. Possibilita o"
                + "\ncadastro de um único Clube no Banco de Dados e permite a gestão de seus"
                + "\nMembros, Funcionários e Agenda de Jogos.", "Sobre", 1);
    }//GEN-LAST:event_itMenuSobreActionPerformed

    private void itMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMenuSairActionPerformed
        sair();
    }//GEN-LAST:event_itMenuSairActionPerformed

    public void abrirFormEquipe(){
        formEquipe = FormEquipe.getInstancia();
        formEquipe.setVisible(true);
    }
    public void abrirFormAgenda(){
        formAgenda = FormAgenda.getInstancia();
        formAgenda.setVisible(true);
    }
    public void abrirFormFunc(){
        formFuncionario = FormFuncionario.getInstancia();
        formFuncionario.setVisible(true);
    }
    public void abrirFormJog(){
        formJog = FormJog.getInstancia();
        formJog.setVisible(true);
    }
    public void abrirFormPres(){
        formPres = FormPres.getInstancia();
        formPres.setVisible(true);
    }
    public void abrirFormTec(){
        formTec = FormTec.getInstancia();
        formTec.setVisible(true);
    }
    
    public void sair(){
        int x = JOptionPane.showConfirmDialog(null, "Deseja realmente sair?", "Sair", JOptionPane.YES_NO_CANCEL_OPTION);
        
        if(x == 0){
            System.exit(0);
        }
    }//fim sair
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itMenuFormAgenda;
    private javax.swing.JMenuItem itMenuFormEquipe;
    private javax.swing.JMenuItem itMenuFormFuncionario;
    private javax.swing.JMenuItem itMenuFormJogador;
    private javax.swing.JMenuItem itMenuFormPresidente;
    private javax.swing.JMenuItem itMenuFormTecnico;
    private javax.swing.JMenuItem itMenuSair;
    private javax.swing.JMenuItem itMenuSobre;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lbPrincipal;
    private javax.swing.JMenu menuMenu;
    // End of variables declaration//GEN-END:variables
}
